DeepCFR PyTorch example
deepmind/open_spiel pull request #226
Opened 2020-05-22 18:17 UTC by MJ10

The algorithms in the library are primarily written in Tensorflow. However, given the generic nature of the rest of the library, algorithms can be written with any learning library. Adding an example demonstrating how to use PyTorch would certainly be helpful for the community, as also mentioned in the [documentation](https://openspiel.readthedocs.io/en/latest/contributing.html#roadmap-and-call-for-contributions).

In this PR I have added a minimal notebook that implements DeepCFR in PyTorch which can serve as a reference.

Feedback welcome!

2020-05-23 13:55 UTC, lanctot commented
This is awesome! Thanks for submitting our first PyTorch contribution! 

> The algorithms in the library are primarily written in Tensorflow. However, given the generic nature of the rest of the library, algorithms can be written with any learning library. Adding an example demonstrating how to use PyTorch would certainly be helpful for the community, as also mentioned in the [documentation](https://openspiel.readthedocs.io/en/latest/contributing.html#roadmap-and-call-for-contributions).

Agree, and in addition to TF and PyTorch, we welcome JAX contributions as well! :)

> In this PR I have added a minimal notebook that implements DeepCFR in PyTorch which can serve as a reference.
> 
> Feedback welcome!

I would love for this to be part of the main library, not just an example in a notebook. How do you feel about making it a callable module like all the other algorithms (maybe in a new subdirectory `python/pytorch`)? And then we could still have a notebook and maybe also a similar usage example in `python/examples`.

I have not looked at the code yet: did you test it to ensure the exploitability goes down in one of the benchmark games?

2020-05-24 12:46 UTC, MJ10 commented
Thanks for the response!

> I would love for this to be part of the main library, not just an example in a notebook. How do you feel about making it a callable module like all the other algorithms (maybe in a new subdirectory `python/pytorch`)? And then we could still have a notebook and maybe also a similar usage example in `python/examples`.

Yes sure. In the notebook, I have implemented a callable module itself. I wasn't sure if it should be part of the main library since an implementation of the algorithm already exists in the library. Will add the module to this PR itself. 
 
> I have not looked at the code yet: did you test it to ensure the exploitability goes down in one of the benchmark games?

Yes I have tested it on kuhn_poker. Should I test it on more games?

2020-05-25 13:47 UTC, lanctot commented
Perfect, thanks. We have several copies of the same algorithm (e.g. in C++ and python) so it is ok to do this with TF vs Pytorch as well, and adding a pytorch directory now will make it easier for future PRs.

Yes I would love it of you could try on Leduc just to see what it gets to, since it is a very common benchmark. No need to make it a test (I guess it will take several hours) but we can compare to the value range we expect to find on Leduc.

Thanks again!

2020-05-25 14:00 UTC, lanctot commented
Whoops, closed the PR by mistake, sorry!

2020-05-25 18:15 UTC, MJ10 commented
Thank you for the response!

> Perfect, thanks. We have several copies of the same algorithm (e.g. in C++ and python) so it is ok to do this with TF vs Pytorch as well, and adding a pytorch directory now will make it easier for future PRs.

Yes that makes sense, I will be pushing the module soon. 

> Yes I would love it of you could try on Leduc just to see what it gets to, since it is a very common benchmark. No need to make it a test (I guess it will take several hours) but we can compare to the value range we expect to find on Leduc.

I tried a small run on LeDuc with the following parameters: 
```python
      policy_network_layers=(32, 32),
      advantage_network_layers=(16, 16),
      num_iterations=400,
      num_traversals=40
```
With the TF Implementation: ```NashConv: 3.0775418037380993```
With the PyTorch Implementation: ```NashConv: 2.9058957077122525```

2020-05-26 04:32 UTC, lanctot commented
Great! 400 iterations is not a lot.. how long did that take? Could you run it for 10000 or 10000, maybe computing the NashConv every 1000? 

You can just run your own if you like. I'm curious if we can get it to below 1.

2020-05-26 05:17 UTC, MJ10 commented
Yes sure, Thanks for the feedback! 
I have started runs with 10000 iterations. I will update here once done.

2020-06-24 18:08 UTC, MJ10 commented
Hey, so sorry for the long delay, got caught up with a few deadlines. 
So I ran the PyTorch and TF versions on Leduc, but was only able to reach NashConv of ~1.4 with both of them. 
Have also added the pytorch version to the library.

2020-06-25 02:18 UTC, lanctot commented
Great, thanks @MJ10 ! Note that we made a few changes to our TF DeepCFR impl recently. 

1.4 NashConv hmm... after how many iterations? And what size nets did you use?

Would be great to sync with @aliyakamercan @ericsteinberger @noambrown on what good hyper-parameters are for Leduc. We don't need to block this PR to get the perfect setup, but would be good to have more confidence that we're reproducing results from the primary authors. 

Eric, Noam: did you ever run Deep CFR on Leduc with small networks (like, same-ish size as the ones used in the NFSP paper)? Would be great if you could point us to a convergence graph so we know what we're trying to achieve.

2020-06-25 18:18 UTC, MJ10 commented
@lanctot  Thanks! I didn't see the changes in the TF DeepCFR, will take a look at that!

2020-07-16 17:28 UTC, finbarrtimbers commented on open_spiel/python/pytorch/deep_cfr.py
> +def reset_params(m):
Can you add a docstring here?

2020-07-16 17:29 UTC, finbarrtimbers commented on open_spiel/python/examples/deep_cfr_pytorch.py
> +  conv = exploitability.nash_conv(
Can you use the C++ exploitability instead (pyspiel.nash_conv)? It's much faster.

2020-07-16 17:32 UTC, finbarrtimbers commented on open_spiel/python/pytorch/deep_cfr.py
> +      Recursively returns expected payoffs for each action.
Can you clarify what exactly is return? I believe it's a float for player.

2020-07-16 17:32 UTC, finbarrtimbers commented on open_spiel/python/pytorch/deep_cfr.py
> +      # Recompute distribution dor numerical errors.
for

2020-07-16 17:33 UTC, finbarrtimbers commented on open_spiel/python/pytorch/deep_cfr.py
> +    """Returns action probabilities dict for a single batch."""
Can you provide a full docstring here?

2020-07-16 17:34 UTC, finbarrtimbers commented on open_spiel/python/pytorch/deep_cfr.py
> +      The average loss obtained on this batch of transitions or `None`.
Can you mention what the type being returned is?

2020-08-09 14:36 UTC, MJ10 commented
Apologies for the extremely long delay. I got caught up with a few other things and didn't get a chance to push the changes

Thank you for the review @finbarrtimbers! I have made changes that you've requested. 

I have also made changes to match the recent fixes to the TF version!

2020-09-10 19:20 UTC, finbarrtimbers commented
Hey sorry to miss this, looking now.

2020-09-10 19:22 UTC, finbarrtimbers requested changes
This lgtm once you fix the remaining print statements!

2020-09-10 19:22 UTC, finbarrtimbers commented on open_spiel/python/examples/deep_cfr_pytorch.py
> +  print("Computed player 0 value: {}".format(average_policy_values[0]))
Can you use logging.info here?

2020-09-10 20:09 UTC, MJ10 commented
Thanks @finbarrtimbers! I have fixed the print statements, I missed those earlier!

2020-09-16 17:27 UTC, finbarrtimbers commented
Merging this internally- should be merged on Github early next week!

2020-09-21 14:56 UTC, MJ10 commented
Thank you @finbarrtimbers! :)

2020-09-22 18:00 UTC, finbarrtimbers commented
Hey! Can you add your test to `python/CMakeLists.txt` & verify that it passes? You'll probably have to add additional imports to `requirements.txt`.

2020-10-16 16:03 UTC, lanctot commented
Hi @MJ10 can you also take a look at https://github.com/deepmind/open_spiel/pull/406 ? I think you will need a similar change.

2020-12-13 16:26 UTC, MJ10 commented
This has been kept open for a while, apologies for the delay @lanctot @finbarrtimbers. I have included the test in the `CMakeLists.txt` and also included the fixes from #406 and #420

2021-02-10 15:13 UTC, merged