Rcfr pytorch
deepmind/open_spiel pull request #425
Opened 2020-10-28 16:08 UTC by Asugawara

Adding RCFR algorithms replacing TensorFlow to PyTorch.(Almost same interface.)
It will be helpful for the community. And this is mentioned in the [documentation.](https://openspiel.readthedocs.io/en/latest/contributing.html#roadmap-and-call-for-contributions)

This PR have some experiment in notebook. Please check it.
Compare exploitability with TensorFlow and PyTorch.
 
Thanks for your development. Open_spiel is very cool oss!!

2020-10-28 16:10 UTC, Asugawara commented
@googlebot I fixed it.

2020-10-28 16:17 UTC, Asugawara commented
@googlebot I fixed it.

2020-10-29 09:22 UTC, lanctot commented
Thanks @Asugawara!

That is quite a lot of new dependencies. Can you explain why you need this many for an RCFR implementation? We generally prefer to keep OpenSpiel as light as possible, and dependencies add long-term maintenance burdens.

The nox tests on Travis-CI are breaking as a result, any idea what is causing that?

2020-10-30 14:44 UTC, Asugawara commented
Thanks for response @lanctot !

This pullrequest added only torch and hypothesis.
torch is PyTorch.
PyTorch’s TestCase class imports hypothesis which uses in rcfr_pytorch_test.py replacing tf.test.TestCase.
(ref:https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L678)

typing_extensions、future,  numpy,  dataclasses are PyTorch's requirements.
(ref:https://github.com/pytorch/pytorch/blob/master/requirements.txt)

attrs, sortedcontainers are hypothesis’s requirements.
(ref:https://github.com/HypothesisWorks/hypothesis/blob/e2db37d0d8c0b2981f87670f92e13cafaa58ba78/hypothesis-python/setup.py#L96)

So, I fix requirements.txt. and the nox tests on Travis-CI will go smoothly.

(Breaking the nox tests on Travis-CI caused by importing dataclass lib)

2020-10-30 15:13 UTC, lanctot commented
> This pullrequest added only torch and hypothesis.

Huh, for some reason I saw many others added to requirements.txt the last time I looked. Maybe it's because I was looking at an individual commit, or maybe you changed it since. Adding these two is ok :)

2020-10-30 15:15 UTC, lanctot commented
> So, I fix requirements.txt. and the nox tests on Travis-CI will go smoothly.
> 
> (Breaking the nox tests on Travis-CI caused by importing dataclass lib)

Ahh, ok, there you go! Perfect.

Ok, we will take a look... Thanks again for the contribution!

(Tagging @dmorrill10 and @michalsustr who might be interested.)

2020-10-30 15:20 UTC, lanctot commented
Let me throw @ssokota into the tag mix as he has more PyTorch experience than anyone I know who is familiar with CFR-style algorithms.

2020-10-30 16:06 UTC, lanctot requested changes

2020-10-30 16:06 UTC, lanctot commented on open_spiel/python/pytorch/rcfr.py
> +from __future__ import absolute_import
At the very top of the file, san you add some text here describing RCFR? Does not have to be long (one or two sentences), but I would also like you to link to the original paper and Dustin's thesis. 

(You can just grab most of the text comment in the TF rcfr.py)

2020-11-13 13:50 UTC, lanctot approved these changes

2020-11-13 14:01 UTC, lanctot requested changes

2020-11-13 16:15 UTC, Asugawara commented on open_spiel/colabs/rcfr_pytorch.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWoAAAD4CAYAAADFAawfAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+
Hi! @lanctot !  Yes I could, those images are not important.
 I remove it.
Thank you for your pointing out.

2020-11-13 18:26 UTC, lanctot commented on open_spiel/colabs/rcfr_pytorch.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWoAAAD4CAYAAADFAawfAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+
Great, thanks!

2020-11-13 18:30 UTC, lanctot commented
Hi @Asugawara , from Travis-CI I noticed there's a dependency problem.. seems like one of PyTorch 1.7's dependencies has problems with Python 3.6. 

Can I ask you to try changing `OS_PYTHON_VERSION` from 3.6 to 3.7 in `.travis.yml`? I'd like to do it in this PR to initiate another integration test to see if it passes. 

I noticed Travis also supports Ubuntu 20.04 now, so I should add it as well.

2020-11-13 18:31 UTC, lanctot requested changes
The tests are failing. See https://github.com/deepmind/open_spiel/pull/425#issuecomment-726949168 for a suggestion to fix them.

2020-11-13 20:57 UTC, Asugawara commented
Thanks. Yes, I will fix it!!!

> seems like one of PyTorch 1.7's dependencies has problems with Python 3.6.
> Can I ask you to try changing OS_PYTHON_VERSION from 3.6 to 3.7

That's what I think, too.

2020-11-14 02:19 UTC, lanctot commented
Perfect. Pushing a new commit will trigger another Travis-CI build so we can check if it worked.

2020-11-15 12:15 UTC, Asugawara commented
In the above problem,  it was occurred by incompatible between dm-haiku requirements and torch requirements.
```
dataclasses==0.7 ; python_version<'3.7'
https://github.com/deepmind/dm-haiku/blob/master/requirements-test.txt#L7

dataclasses; python_version<“3.7"
https://github.com/pytorch/pytorch/blob/master/requirements.txt#L8

FYI: the latest version is 0.8
```

But, The nox tests on Travis-CI are breaking with the error message saying “An error occurred while generating the build script.”
Do you have any ideas?Travis’s issue?

2020-11-15 13:39 UTC, lanctot commented
Yeah that is my guess. I restarted the Travis build, let's see if it was just a fluke.

2020-11-16 00:11 UTC, lanctot approved these changes

2020-11-18 00:45 UTC, Asugawara commented
Thank you Mr. @lanctot !

2020-11-18 01:35 UTC, lanctot commented
> Thank you Dr. @lanctot !

Very nicely done and well tested, partly benefitting from the TF impl, but still very well adspted.

This is the first officially imported PyTorch PR. A milestone for the project, congrats!

2020-11-21 09:32 UTC, merged