Add a test for creation of a shared library.
deepmind/open_spiel pull request #432
Opened 2020-11-02 18:36 UTC by michalsustr

2020-11-04 09:43 UTC, michalsustr commented
Not sure why, but the last travis failure was due julia, not the new ortools.

2020-11-04 12:29 UTC, michalsustr commented
Ok, probably Travis was just having a bad day, as it sometimes does :)

2020-11-04 13:54 UTC, lanctot approved these changes
Neat, thanks!

2020-11-04 14:02 UTC, lanctot commented on open_spiel/scripts/install.sh
> +  DOWNLOAD_URL="https://github.com/google/or-tools/releases/download/v8.0/or-tools_ubuntu-18.04_v8.0.8283.tar.gz"
Can we have an if Mac OS download X, else download Y here?

2020-11-04 14:05 UTC, lanctot requested changes

2020-11-04 14:05 UTC, lanctot commented on .travis.yml
> +      - BUILD_WITH_ORTOOLS="ON"
Can we add something similar for MacOS? Should only require a few small changes to install.sh.

2020-11-04 14:07 UTC, lanctot commented on .travis.yml
> +      - BUILD_WITH_ORTOOLS="ON"
Actually, never mind. I don't think I've tested the shared lib on MacOS yet, but will soon.

2020-11-06 02:59 UTC, lanctot commented on open_spiel/scripts/install.sh
> +  DOWNLOAD_URL="https://github.com/google/or-tools/releases/download/v8.0/or-tools_ubuntu-18.04_v8.0.8283.tar.gz"
Oops, I realized I had never sent that last message, sorry...! 

Easy to do on my side... but easier for you to test directly on Travis by just doing more commits, so let's do that. 

Basically, I think all it takes is checking that BUILD_WITH_OR_TOOLS is something other than "OFF" and copy that to DOWNLOAD_URL. And then in travis.yml just use the Ubuntu 18.04 link. 

We should clarify this in the documentation (like the main CMakeLists too, and maybe include all the common links: MacOS, Ubuntu 18.04 and Ubuntu 20.04 so people can copy/paste.

Thanks for doing this.. sorry for the run-around!

2020-11-08 13:30 UTC, michalsustr commented
I rather made the download url a separate global variable, as I think it's better to have a consistent implicit type system (bool for `BUILD_WITH_XXX`) in the configs, rather than mixing them up (bool or optional<string>).

2020-11-08 14:25 UTC, lanctot commented
Ok great thanks!

2020-11-08 14:26 UTC, lanctot approved these changes

2020-11-09 15:24 UTC, merged