Amazons implementation v1
deepmind/open_spiel pull request #771
Opened 2022-01-23 02:50 UTC by selfsim

Hello @lanctot !
After a while away from RL I am back to work on this project. Here is a new PR. I hope this works.
Let me know!
Cheers,
selfsim

2022-01-24 21:03 UTC, lanctot commented
Awesome! Welcome back. Can I ask you to merge the latest changes from master to fix the conflict?

2022-01-24 21:05 UTC, lanctot commented
Should be as simple as running

```
git pull origin master  # fetch changes and commit the merge locally
git push
```

2022-01-24 21:08 UTC, lanctot commented
(In this case I think the merge is easy, you can even do it via the 'Resolve conflict' button above.

2022-01-26 00:43 UTC, selfsim commented
@lanctot done

2022-01-26 01:33 UTC, lanctot requested changes
Can you add Amazons to the games list (see docs/games.md)

2022-01-26 01:33 UTC, lanctot commented on open_spiel/python/tests/pyspiel_test.py
> +EXPECTED_GAMES = set([
Did you merge from master..? This should be frozenset

2022-01-26 01:33 UTC, lanctot commented on open_spiel/games/amazons_test.cc
> +
Remove the blank lines

2022-01-27 13:22 UTC, lanctot commented
Hi @selfsim, looks good! I've imported it. It's currently undergoing internal review now, so probably will be merged by the next update.

A few quick C++ tips:

- Avoid `using namespace std`. It's customary to either use specific things (e.g. `using std::min`) or just prepend the namespace to the functions when you use them. The former is preferred when the namespace is long and there are many uses in the file.
- Don't use C-style casts. Prefer C++ style casts: e.g. `static_cast<unsigned char>(value)`
- Don't use sprintf. Use `absl::StrCat`, `absl::StrAppend`, or `absl::StrFormat`.

Thanks again... great game addition to OpenSpiel!

2022-01-28 01:44 UTC, selfsim commented
@lanctot thanks for the review! I will be refactoring the code as my C++ improves. 

I have a question:

Within my game implementation a move is broken into submoves; instead of giving a value for a move (select amazon, move amazon, shoot arrow) in one go, the move is built incrementally. One idea I had was to take a hierarchical RL approach towards agent design for amazons, where the subturn policies are learned by individual networks. Do you think this would be possible within the open_spiel framework?

2022-01-31 09:39 UTC, merged