Liar's Poker Game
deepmind/open_spiel pull request #982
Opened 2022-12-22 22:21 UTC by w07wong

2022-12-23 12:42 UTC, lanctot commented
Thanks!

2022-12-23 14:16 UTC, lanctot commented
The wheels are failing their tests, but I don't think it's related to your changes. 

See https://github.com/deepmind/open_spiel/pull/983. 

This happens every few months, usually when a change is made to the CI servers/setups. I'll try to take a look soon in #983 and will let you know when a fix is merged into master so you can pull and rerun the tests.

2022-12-30 18:10 UTC, lanctot commented
Quick update: I've managed to fix the problem via this PR: https://github.com/deepmind/open_spiel/pull/983. I've imported it into our internal repos but I will need a review-- everyone is currently on holidays, so it might only happen in early January. Once it's submitted, I will sync to github and let you know, then you'll only need to pull changes from master and commit the merge to re-trigger the tests.

2023-01-16 14:54 UTC, bartdevylder requested changes
Sorry or the rreview delay and thank you for adding this game and already providing unittests!

2023-01-16 14:54 UTC, bartdevylder commented on open_spiel/python/games/liars_poker.py
> +    self._current_bid = -1
I'd try to be more consistent with the use of the term 'bid': in the argument to _decode_bit(bit) it is assumed not to contain the offset, but self._current_bid contains the offset. Maybe remove the offset from self._current_bid, or rename to _current_action?

2023-01-16 14:54 UTC, bartdevylder commented on open_spiel/python/games/liars_poker.py
> +    self._game_over = False
self._game_over can probably be removed by redefining
is_terminal(): self._winner >= 0 or self._loser >= 0 
?

2023-01-16 14:54 UTC, bartdevylder commented on open_spiel/python/games/liars_poker.py
> +    self._current_player = 0
Maybe add short comment that self._current_player is only the valid current_player when cards have been dealt (otherwise it's chance)

2023-01-16 14:54 UTC, bartdevylder commented on open_spiel/integration_tests/playthroughs/python_liars_poker.txt
> +StringLegalActions() = ["Challenge", "Bet", "Bet", "Bet", "Bet"]
Different action id's should have different strings, so probably an amount /count needs to be added to Bet

2023-01-16 14:54 UTC, bartdevylder commented on open_spiel/python/games/liars_poker.py
> +      return "Bet"
(see also comment in playthrough):
Different action id's should have different strings, so probably an amount /count needs to be added to Bet

2023-01-16 14:54 UTC, bartdevylder commented on open_spiel/python/games/liars_poker.py
> +      for b in range(max(self._bid_offset, self._current_bid + 1), self._max_bid + 1):
I think this might be better readable by looping over the bid's without offset and finally e.g.
actions.append(bid + BID_ACTION_OFFSET)

2023-01-18 14:36 UTC, bartdevylder commented
Thanks for addressing the comments! The PR will be merged into openspiel soon

2023-01-23 12:57 UTC, merged